# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.5
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: true
# uncomment the following lines to override the default test script
env:
  global:
    DOWNLOADROMS=true
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("AtariAlgos"); Pkg.test("AtariAlgos"; coverage=true)'
